### ISSUE TITLE
Content relations are not removed when the according content is deleted

### ISSUE THREAD

**Issue by Biont** [inpsyde/multilingual-press#143]
For some reason, MLP does not clean up its database entries when a post is (permanently) deleted. That means the references in the `*_multilingual_linked` table still point to non-existing posts.
This is either a regression or a pretty substantial oversight and should be fixed soon.

 * There is no code that hooks into `delete_post` (or anything matching that pattern)
 * `Mlp_Content_Relations::delete_relation()` is only called internally and by the Term Translator

It seems this feature is simply missing entirely (or hasn't survived refactoring/merges).

---

**TODOs:**

* [x] Delete post relations on post deletion.
* [x] Delete term relations on term deletion.
* [x] Delete all entries in the `multilingual_linked` (!) table for posts/terms that don't exist anymore.
  * [x] Do the same on every (re-)activation, but for the new (!) table (in case there have been posts deleted while MLP was inactive)

**Comment by tfrommen** [comment]
This is, of course, suboptimal. However, as this also should include a cleanup routine to delete content relations entries including not existing posts, and because the current behavior doesn't actually _break_ anything, this will be postponed (to 2.3.0).

**Comment by tfrommen** [comment]
This is also true for terms.

**Comment by tfrommen** [comment]
Related to #171.

**Comment by tfrommen** [comment]
**Update:** The current behavior (i.e., in the `2.3` branch) actually **does** break things. All the things that rely on [`Mlp_Language_Api::get_translations()`](https://github.com/inpsyde/multilingual-press/blob/b1c9f511874cf02491d6ba27e15e2de5ad13ed24/src/inc/language-api/Mlp_Language_Api.php#L200), that is.

If the content relations table contains references to posts or terms that do not exist anymore, the method does not return any data for the according site.

The relevant lines are here:
* [defining a post translation invalid](https://github.com/inpsyde/multilingual-press/blob/b1c9f511874cf02491d6ba27e15e2de5ad13ed24/src/inc/language-api/Mlp_Language_Api.php#L282);
* [defining a term translation invalid](https://github.com/inpsyde/multilingual-press/blob/b1c9f511874cf02491d6ba27e15e2de5ad13ed24/src/inc/language-api/Mlp_Language_Api.php#L268);
* [unsetting the according data](https://github.com/inpsyde/multilingual-press/blob/b1c9f511874cf02491d6ba27e15e2de5ad13ed24/src/inc/language-api/Mlp_Language_Api.php#L322).

**Comment by tfrommen** [comment]
Closed in the according branch.
