### ISSUE TITLE
Refactor (Admin) JavaScript

### ISSUE THREAD

**Issue by Biont** [inpsyde/multilingual-press#168]
This issue will keep track of commits and discussion concerning the planned refactoring of MLP's (back-end) JavaScript.

Currently, the JS is very barebone and closed down. There are a couple of private objects hosting a bunch of functions that we need to implement our back-end functionality.
Now, for small things like the term translation selectors, this is probably not a big deal. No need to overcomplicate things.

But on the post translator, or more specifically, the Translation meta box, this approach makes it impossible (or at least rather cumbersome) to implement custom functionality. If we're dedicated to making it easy for developers to extend MLP, our JS should not stand in the way of doing that.

I would propose reworking the _Post Editor_ JS so that each Translation meta box, as well as all elements in it, are turned into Backbone objects. This should make it very easy to customize and extend them.

**Roadmap:**
* [x] `admin.js`
  * [x] `admin.js: copyPost()` -> `post-translator/CopyPost.js`
  * [x] `admin.js: setToggle()` -> `common/Common.js`
  * [x] ~~`advanced_translator.js`~~
  * [x] `nav_menu_meta_box.js` -> `nav-menus/NavMenus.js`
  * [x] `plugin_activator.js` -> `network/AddNewSite.js`
  * [x] `relationship_control.js` -> `post-translator/RelationshipControl.js`
  * [x] `relationship_control.js` -> `post-translator/RCSearch.js`
  * [x] `term_translator.js` -> `term-translator/TermTranslator.js`
* [x] `frontend.js`
  * [x] `quicklink.js` -> `quicklink/Quicklinks.js`
* [x] inline scripts
  * [x] `Mlp_New_Site_View.php` -> `network/AddNewSite.js`
  * [x] `Mlp_Relationship_Control_Meta_Box_View.php` -> `post-translator/RelationshipControl.js`
  * [x] `Mlp_User_Backend_Language.php` -> `user-settings/UserBackendLanguage.js`
* [ ] Provide access to Copy Post feature for third-party developers
  * [ ] `post-translator/CopyPost.js: copyPostData`: allow custom data to be added
  * [x] `post-translator/CopyPost.js: updatePostData`: fire event and pass data
  * [x] `Mlp_Advanced_Translator::process_post_data`: provide a filter for the `$data` array
